version: '3.8'

services:
  patra-server:
    image: iud2i/patra-server:latest
    ports:
      - "5002:5002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PWD=${NEO4J_PWD}