version: '3.8'

services:
  patra-server:
    image: iud2i/patra-server:latest
    ports:
      - "5002:5002"
    env_file:
      - config.env
    networks:
      - ckn-network

networks:
  ckn-network:
    external: True