services:
  neo4j-db:
    image: neo4j:5.21.0-community
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/PWD_HERE
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    healthcheck:
      test: ["CMD-SHELL", "neo4j status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - patra-network
    volumes:
      - neo4j_data:/data
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G
        reservations:
          cpus: '3'
          memory: 6G
  rest-server:
    build:
      context: ..
      dockerfile: benchmarking/rest/Dockerfile
    container_name: rest_server
    ports:
      - "5002:5002"
    depends_on:
      - neo4j-db
    environment:
      - NEO4J_URI=bolt://neo4j-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PWD=PWD_HERE
      - BENCHMARK=True
    networks:
      - patra-network
    volumes:
      - ./timings:/app/timings/rest
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

  mcp-server:
    build:
      context: ..
      dockerfile: benchmarking/native_mcp/Dockerfile
    container_name: mcp_server
    ports:
      - "8050:8050"
    environment:
      - NEO4J_URI=bolt://neo4j-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PWD=PWD_HERE
    networks:
      - patra-network
    volumes:
      - ./timings:/app/timings/native_mcp
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
  
  layered-mcp-server:
    build:
      context: ..
      dockerfile: benchmarking/layered_mcp/Dockerfile
    container_name: layered_mcp_server
    ports:
      - "8051:8051"
    environment:
      - REST_API_BASE_URL=http://rest-server:5002
    depends_on:
      - rest-server
    networks:
      - patra-network
    volumes:
      - ./timings:/app/timings/layered_mcp
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

networks:
  patra-network:
    driver: bridge

volumes:
  neo4j_data:
    driver: local